<div class="fieldset">
	<div class="grid" id="grid_001">
    	<table cellpadding="0" cellspacing="0" class="border">
        	<tbody>
            	<tr class="headings" id="headings_001">
                	<th><?php echo Mage::helper('album')->__('Title')?></th>
                	<th><?php echo Mage::helper('album')->__('Separate Purchase')?></th>
                	<th><?php echo Mage::helper('album')->__('Price')?></th>
                	<th><?php echo Mage::helper('album')->__('File')?></th>
                	<th><?php echo Mage::helper('album')->__('Sample')?></th>
                	<th><?php echo Mage::helper('album')->__('Order')?></th>
                	<th></th>
            	</tr>
            </tbody>
        </table>
    </div>
</div>
            
